#!/bin/sh
echo "Restoring config files. PLease Wait..."
cd ~/backup
# alias config="mkdir -p ~/.config"
alias di="mkdir -p"
alias cp="cp -r"
path=$(pwd)
cd ~/.config
config=$(pwd)
cd $path


di $config/ranger
di $config/i3
di $config/polybar
di ~/.polybar-scripts
di ~/.scripts
di ~/Pictures
di ~/Pictures/Wallpapers
di $config/kitty
di $config/dunst
di $config/picom
di $config/gtk-3.0
di $config/bspwm
di $config/sxhkd

sudo mkdir -p  /etc/lightdm
sudo mkdir -p /usr/share/themes
sudo mkdir -P /usr/share/backgrounds
sudo mkdir -P /usr/share/icons

sudo cp $path/backgrounds/* 		/usr/share/backgrounds
cp $path/backgrounds/* 			~/Pictures/Wallpapers
sudo cp -r $path/themes/*		/usr/share/themes/
sudo cp -r $path/icons/*		/usr/share/icons/

# cp $config

cp $path/ranger/*			$config/ranger/
cp $path/i3/*				$config/i3/ 
cp $path/polybar/*			$config/polybar
cp $path/kitty/*			$config/kitty
cp $path/dunst/*			$config/dunst
cp $path/picom/*			$config/picom
cp $path/gtk-3.0/*			$config/gtk-3.0
cp $path/bspwm/*			$config/bspwm
cp $path/sxhkd/*			$config/sxhkd
sudo cp $path/gtk-3.0/*			$config/gtk-3.0


cp $path/polybar-scripts/*		$HOME/.polybar-scripts/
cp $path/scripts/*			$HOME/.scripts/

cp $path/bash_profile			$HOME/.bash_profile
cp $path/bashrc				$HOME/.bashrc
cp $path/vimrc				$HOME/.vimrc
cp $path/profile			$HOME/.profile
cp $path/gtkrc-2.0			$HOME/.gtkrc-2.0
sudo cp $path/gtkrc-2.0			$HOME/.gtkrc-2.0
cp $path/compton.conf			$config/compton.conf

sudo cp $path/lightdm/*			/etc/lightdm/
sync
echo "Done! Enjoy"
