#!/bin/sh
echo "Restoring config files. PLease Wait..."
cd ~/backup
# alias config="mkdir -p ~/.config"
alias di="mkdir -p"
alias cp="cp -r"
path=$(pwd)
cd ~/.config
config=$(pwd)
cd $path


di $config/ranger
di $config/i3
di $config/polybar
di $HOME/.scripts
di $HOME/Pictures
di $HOME/Pictures/Wallpapers
di $HOME/.templates
di $config/kitty
di $config/dunst
di $config/picom
di $config/gtk-3.0
di $config/gtk-4.0
di $config/bspwm
di $config/sxhkd
di $config/dconf
di $config/dwm

sudo mkdir -p /etc/lightdm
sudo mkdir -p /usr/share/themes
sudo mkdir -p /usr/share/backgrounds
sudo mkdir -p /usr/share/icons

sudo cp $path/backgrounds/* 		/usr/share/backgrounds
cp $path/backgrounds/* 			~/Pictures/Wallpapers
sudo cp -r $path/themes/*		/usr/share/themes/
sudo cp -r $path/icons/*		/usr/share/icons/

# cp $config

cp $path/ranger/*			$config/ranger/
cp $path/i3/*				$config/i3/ 
cp $path/polybar/*			$config/polybar
cp $path/kitty/*			$config/kitty
cp $path/dunst/*			$config/dunst
cp $path/picom/*			$config/picom
cp $path/gtk-3.0/*			$config/gtk-3.0
cp $path/gtk-4.0/*			$config/gtk-4.0
cp $path/bspwm/*			$config/bspwm
cp $path/sxhkd/*			$config/sxhkd
cp $path/dconf/*			$config/dconf
cp $path/dwm/*				$config/dwm/
sudo cp $path/gtk-3.0/*			$config/gtk-3.0
cp -r $path/.icons/			$HOME/


cp $path/polybar-scripts/*		$HOME/.polybar-scripts/
cp $path/scripts/*			$HOME/.scripts/

cp $path/bash_profile			$HOME/.bash_profile
cp $path/bashrc				$HOME/.bashrc
cp $path/vimrc				$HOME/.vimrc
cp $path/profile			$HOME/.profile
cp $path/xinitrc			$HOME/.xinitrc
cp $path/gtkrc-2.0			$HOME/.gtkrc-2.0
sudo cp $path/gtkrc-2.0			$HOME/.gtkrc-2.0
cp $path/compton.conf			$config/compton.conf

sudo cp $path/lightdm/*			/etc/lightdm/

#Generating wallpaper list for gnome-settings
python << END
import os
import xml.etree.cElementTree as ET

workdir = '/usr/share/backgrounds'
#os.chdir('/usr/share/gnome-background-properties')
ls = os.listdir(workdir)

root = ET.Element("wallpapers")
for i in ls:
	if os.path.isdir(i) == False:
		wallpaper = ET.SubElement(root, "wallpaper", deleted="false")
		ET.SubElement(wallpaper, "name").text='background '  + i
		ET.SubElement(wallpaper, "filename").text=workdir + '/' + i
		ET.SubElement(wallpaper, "options").text='zoom'
		ET.SubElement(root, "pcolor").text='#ffffff'
		ET.SubElement(root, "scolor").text='#000000'
tree = ET.ElementTree(root)
tree.write("gnome-backgrounds.xml")

END
xmllint --format gnome-backgrounds.xml >> cos.xml
sudo cp cos.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
rm cos.xml
rm gnome-backgrounds.xml


sync

echo "Done! Enjoy"
