#!/bin/sh
echo "Restoring config files. PLease Wait..."
cd ~/backup
# alias config="mkdir -p ~/.config"
alias di="mkdir -p"
alias cp="cp -r"
path=$(pwd)
cd ~/.config
config=$(pwd)
cd $path


di $config/ranger
di $config/i3
di $config/polybar
di $HOME/polybar-scripts
di $HOME/.scripts
di $HOME/Pictures
di $HOME/Pictures/Wallpapers
di $HOME/.templates
di $config/kitty
di $config/dunst
di $config/picom
di $config/gtk-3.0
di $config/gtk-4.0
di $config/bspwm
di $config/sxhkd
di $config/dconf
di $config/dwm

sudo mkdir -p /etc/lightdm
sudo mkdir -p /usr/share/themes
sudo mkdir -p /usr/share/backgrounds
sudo mkdir -p /usr/share/icons

sudo cp $path/backgrounds/* 		/usr/share/backgrounds
cp $path/backgrounds/* 			~/Pictures/Wallpapers
sudo cp -r $path/themes/*		/usr/share/themes/
sudo cp -r $path/icons/*		/usr/share/icons/

# cp $config

cp $path/ranger/*			$config/ranger/
cp $path/i3/*				$config/i3/ 
cp $path/polybar/*			$config/polybar
cp $path/kitty/*			$config/kitty
cp $path/dunst/*			$config/dunst
cp $path/picom/*			$config/picom
cp $path/gtk-3.0/*			$config/gtk-3.0
cp $path/gtk-4.0/*			$config/gtk-4.0
cp $path/bspwm/*			$config/bspwm
cp $path/sxhkd/*			$config/sxhkd
cp $path/dconf/*			$config/dconf
cp $path/dwm/*				$config/dwm/
sudo cp $path/gtk-3.0/*			$config/gtk-3.0
cp -r $path/.icons/			$HOME/


cp $path/polybar-scripts/*		$HOME/.polybar-scripts/
cp $path/scripts/*			$HOME/.scripts/

cp $path/bash_profile			$HOME/.bash_profile
cp $path/bashrc				$HOME/.bashrc
cp $path/vimrc				$HOME/.vimrc
cp $path/profile			$HOME/.profile
cp $path/xinitrc			$HOME/.xinitrc
cp $path/gtkrc-2.0			$HOME/.gtkrc-2.0
sudo cp $path/gtkrc-2.0			$HOME/.gtkrc-2.0
cp $path/compton.conf			$config/compton.conf

sudo cp $path/lightdm/*			/etc/lightdm/

#Generating wallpaper list for gnome-settings


cd /usr/share/backgrounds/

declare -a array=($(ls))
#array=($(ls))
#echo ${array[@]}

arraylength=${#array[@]}


echo '<?xml version="1.0"?>' > ~/test.xml
echo '<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">' >> ~/test.xml
echo '<wallpapers>' >> ~/test.xml





for (( i=1; i<${arraylength}+1; i++ ));
#for i in "$array"
do
	#echo "$array[@]"
	#echo $i " / " ${arraylength} " : " ${array[$i-1]}
	echo ${array[$i-1]}

	#echo ${array[$i-1]} >> ~/test.xml
	echo "	<wallpaper deleted='false'>
		<name>background ${array[$i-1]}</name>
		<filename>/usr/share/backgrounds/${array[$i-1]}</filename>
		<options>zoom</options>
    <pcolor>#ffffff</pcolor>
    <scolor>#000000</scolor>
	</wallpaper>" >> ~/test.xml
done
echo '</wallpapers>' >> ~/test.xml

sudo mkdir -p  /usr/share/gnome-background-properties/
sudo cp ~/test.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
rm ~/test.xml

sync

echo "Done! Enjoy"
