#! /bin/sh
killall picom
picom -bcCGfF -o 0.38 -O 200 -I 200 -t 0 -l 0 -r 3 -D2 -m 0.88 &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
~/.config/polybar/launch.sh & # Status bar

xsetroot -cursor_name left_ptr & # X cursor fix
dunst & # Notifications
lxsession &
#feh --bg-fill ~/Pictures/Wallpapers/space-neon.jpg & # Wallpaper
sxhkd & # Keyboard shortcuts
xss-lock --transfer-sleep-lock -- betterlockscreen -l &
exec $HOME/.config/polybar/launch.sh &
wal -R &
polybar -q example & 
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
setxkbmap -layout pl
nm-applet &
bspc config border_width         2
bspc config window_gap           16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

# bspc config single_monocle	 true

bspc rule -a origin.exe state=floating
