#!/bin/bash
deploy-flatpak
flat_install="flatpak install --assumeyes"
$flat_install flathub com.jetbrains.IntelliJ-IDEA-Community
$flat_install flathub com.google.AndroidStudio
$flat_install flathub com.github.marktext.marktext

if [[ -f /usr/share/pacman ]]
then
	if [[ ! -f /usr/bin/yay ]]
	then
		$install git base-develop
		git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm
	fi
	yay -S --noconfirm code vim curl 
fi

curl https://raw.githubusercontent.com/edwardbas-pl/backup/master/vimrc -o $HOME/.vimrc
vim +PlugInstall +YcmRestartServer +qall

