#!/bin/bash
deploy-flatpak

if [[ -f /usr/bin/pacman ]]
then
	if [[ ! -f /usr/bin/yay ]]
	then
		$install git base-develop
		git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm
		sudo systemctl enable --now jellyfin
		GPU=$(lspci | grep -i --color "vga\|3d\|2d")
		if [[ ${GPU} == *Radeon* ]];
		then
			#echo "your GPU vendor is AMD"
			$install libva-mesa-driver mesa vdpau
		fi
		if [[ ${GPU} == *Intel* ]];
		then
			#echo your GPU vendor is Intel
			$install intel-media-driver
		fi
		if [[ ${GPU} == *NV* ]];
		then
			#echo your GPU vendor is NVidia
			$install nvidia-utils
		fi

	fi
else
	print "distro unsuported. I wont install jellyfin media sewrver... Only player"
fi


flatpak install flathub com.github.iwalton3.jellyfin-media-player
