#!/bin/bash
if [[  ! -f /usr/bin/flatpak ]]
then

	if [[ -f /usr/bin/pacman ]]
	then
		install="sudo pacman -S --noconfirm"	
	fi
	if [[ -f /usr/bin/dnf ]]
	then
		install="sudo dnf install -y"
	fi
	if [[ -f /usr/bin/apt ]]
	then
		intall="sudo apt install -y"
	$install flatpak
else
	exit
fi
