#!/bin/sh
echo "Backing Up dotfiles. Please wait..." && notify-send "Backing Up dotfiles. Please wait..."
cd
mkdir -p backup
cd backup
# alias config="mkdir -p ~/.config"
alias di="mkdir -p"
alias cp="cp -r"
path=$(pwd)
cd ~/.config
config=$(pwd)
cd $path

di bspwm
di sxhkd
di ranger
di i3
di polybar
di polybar-scripts
di scripts
di backgrounds
di kitty
di dunst
di picom
di lightdm
di themes
di gtk-3.0

sudo mkdir -p /usr/share/backgrounds/
sudo cp -r ~/Pictures/Wallpapers/* /usr/share/backgrounds
cp -r /usr/share/backgrounds/* 	$path/backgrounds
cp -r /usr/share/themes/*	$path/themes/

# cp $config

cp $config/ranger/*		$path/ranger/
cp $config/i3/*			$path/i3/
cp $config/polybar/*		$path/polybar
cp $config/kitty/*		$path/kitty
cp $config/dunst/*		$path/dunst
cp $config/picom/*		$path/picom
cp $config/gtk-3.0/*		$path/gtk-3.0/
cp $config/bspwm/*		$path/bspwm/
cp $config/sxhkd/*		$path/sxhkd/

cp $HOME/.polybar-scripts/*	$path/polybar-scripts/
cp $HOME/.scripts/*		$path/scripts

cp $HOME/.bash_profile		$path/bash_profile
cp $HOME/.bashrc		$path/bashrc
cp $HOME/.vimrc			$path/vimrc
cp $HOME/.profile		$path/profile
cp ~/.scripts/Restore		$path/Restore
cp /etc/lightdm/*		$path/lightdm
cp ~/.gtkrc-2.0			$path/gtkrc-2.0
sync
echo "Done!"
notify-send "Dotfiles copied to $HOME/backup/"
