#!/bin/python3
import os
import sys
import shutil
#TODO make it case sensitive or insesitive

def main( *args ):
    pwd = os.getcwd()
    ls = os.listdir(pwd)
    if len(args) == 0:
        print("give me a pattern")
        pattern = input()
    else:
        pattern = args[0]

    if pattern in ls:
        if os.path.isdir(pattern) == True:
            ls.remove(pattern)
            pass
    else:
        os.mkdir(pattern)
    target_dir = pattern
    for i in ls:
        if pattern in i:
            target = target_dir + "/" + i
            shutil.move( i , target)

    pass

if __name__ == "__main__":
    if len(sys.argv) > 1:
        main(sys.argv[1])
    else:
        main()


