#!/bin/python3
import shutil
import sys
import os

class PathDoesNotExist(Exception):
    def __init__(self):
        self.message = "provided path does not exist"
    def __str__(self):
        return self.message

def import_play_dir(playlist_file,target_dir):
    dir_name=os.path.splitext(playlist_file)[0] #get rid of playlist file extension
    dir_name=dir_name.replace(" ","_")
    dir_to_create = target_dir+"/"+dir_name
    #print("dir to create: " + dir_to_create)
    os.system("mkdir -p " + dir_to_create)
    raw_list = []
    list = []
    with open(playlist_file) as love:
        raw_list = love.readlines()
    for i in raw_list:
        i = i.replace("\n","")
        #print(i)
        list.append(i)
        shutil.copy2( i , dir_to_create+"/")
    return list

def filter_list(full_list, excludes):
    list = []
    for i in excludes:
        for j in full_list:
            if i != j:
                list.append(i)
    print(list)
    return list

def get_playlists(dir):
    ls = os.listdir(dir)
    list = []
    for i in ls:
        extension = os.path.splitext(i)[1]
        if extension == ".m3u":
            print(i +" "+ "is a playlist")
            list.append(i)
    return list

def main(arg):
    #print(len(arg))
    global cwd
    cwd = os.getcwd()
#    ls = os.listdir(cwd)
    moved_list = []
    if len(arg) > 1:
        path=arg[1]
        raw_playlists = get_playlists(cwd)
        for i in raw_playlists:
            moved_list.append(import_play_dir(i,path))
    else:
        print("number of parameters is invalid")

if __name__ == "__main__":
    try:
        if os.path.exists(sys.argv[1]) == False:
            raise PathDoesNotExist
        else:
            main(sys.argv)
    except PathDoesNotExist:
        print('provided path does not exist')
        quit()


