#!/bin/bash
yt(){

	sh *.yt
	youtube-dl -a *.yt
	sh crawl.sh
}

crawl(){
	for i in $(ls -d */);
	do                     
        	echo ${i%%/}    
	        cd ${i%%/}
		crawl 
		yt
	        cd ..
	done
}

crawl
