#!/bin/bash

cd /usr/share/backgrounds/

declare -a array=($(ls))
#array=($(ls))
#echo ${array[@]}

arraylength=${#array[@]}
dir='test.xml'

echo '<?xml version="1.0"?>' > ~/test.xml
echo '<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">' >> ~/test.xml
echo '<wallpaper>' >> ~/test.xml





for (( i=1; i<${arraylength}+1; i++ ));
#for i in "$array"
do
	#echo "$array[@]"
	#echo $i " / " ${arraylength} " : " ${array[$i-1]}
	#echo ${array[$i-1]}

	#echo ${array[$i-1]} >> ~/test.xml
	echo "	<wallpaper deleted='false'>
		<name>background ${array[$i-1]}</name>
		<filename>/usr/share/backgrounds/${array[$i-1]}</filename>
		<options>zoom</options>
    		<pcolor>#ffffff</pcolor>
    		<scolor>#000000</scolor>
	</wallpaper>" >> ~/test.xml
done
echo '</wallpaper>' >> ~/test.xml

echo ${arraylength}

sudo cp /usr/share/gnome-background-properties/gnome-backgrounds.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml.old
sudo cp ~/test.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml 		
