#!/bin/bash


http=$(sudo systemctl status httpd | grep Active | awk '{print $2 }')
mysql=$(sudo systemctl status mysqld | grep Active | awk '{print $2 }')



echo "httpd status: "$http
echo "mysqld status: "$mysql

if [[("$http" == "active" && "$mysql" == "active")]]; then
	sudo systemctl stop httpd
	sudo systemctl stop mysqld

	notify-send "all services are now inactive"
elif [[("$http" == "inactive" && "$mysql" == "inactive")]]; then
	sudo systemctl start httpd
	sudo systemctl start mysqld
	notify-send "all services are now active" 
elif [[("$http" == "inactive" && "$mysql" == "active")]]; then
	notify-send "http server was not active. Activating Now.."
	sudo systemctl start httpd
	notify-send "all services are now active"
elif [[("$http" == "active" && "$mysql" == "inactive")]]; then
	notify-send "mysql server was not active. Activating Now.."
	sudo systemctl start mysqld
	notify-send "all services are now active"
else
	notify-send --urgency=critical "Something went wrong"
fi
