#!/bin/sh

xrandr | grep connected | awk '{print $1,  $2 }'

echo  "Now you see witch dispays are connected. please write Name of one witch has to be primary display:"
read -p "Display name: " display
echo "you chose $display. Seting it as a primary display output..."
xrandr --output $display --primary
