#!/bin/bash
echo "Restoring config files. PLease Wait..."
cd ~/backup
mkdir -p $HOME/.config
# alias config="mkdir -p ~/.config"
#alias di="mkdir -p"
alias cp="cp -r"
path=$(pwd)
cd ~/.config
config=$(pwd)
cd $path


mkdir -p $config/ranger
mkdir -p $config/i3
mkdir -p $config/polybar
mkdir -p $HOME/.scripts
mkdir -p $HOME/Pictures
mkdir -p $HOME/Pictures/Wallpapers
mkdir -p $HOME/.templates
mkdir -p $HOME/.local/share/nemo/actions
mkdir -p $config/kitty
mkdir -p $config/dunst
mkdir -p $config/picom
mkdir -p $config/gtk-3.0
mkdir -p $config/gtk-4.0
mkdir -p $config/bspwm
mkdir -p $config/sxhkd
mkdir -p $config/dconf
mkdir -p $config/dwm
# mkdir -p $config/nvim
mkdir -p $config/hypr
mkdir -p $config/waybar
mkdir -p $config/rofi

sudo mkdir -p /etc/lightdm
sudo mkdir -p /usr/share/themes
sudo mkdir -p /usr/share/backgrounds
sudo mkdir -p /usr/share/icons

sudo cp -r $path/backgrounds/* 		/usr/share/backgrounds
cp -r $path/backgrounds/* 			~/Pictures/Wallpapers
sudo cp -r $path/themes/*		/usr/share/themes/
sudo cp -r $path/icons/*		/usr/share/icons/

# cp $config
cp $path/ranger/*			$config/ranger/
cp $path/i3/*				$config/i3/ 
cp $path/polybar/*			$config/polybar
cp $path/kitty/*			$config/kitty
cp $path/dunst/*			$config/dunst
cp $path/picom/*			$config/picom
cp $path/gtk-3.0/*			$config/gtk-3.0
cp $path/gtk-4.0/*			$config/gtk-4.0
cp $path/bspwm/*			$config/bspwm
cp $path/sxhkd/*			$config/sxhkd
cp $path/dconf/*			$config/dconf
cp $path/dwm/*				$config/dwm/
cp $path/nemo/actions       $HOME/.local/share/nemo/actions
# cp $path/nvim/init.lua				$config/nvim/
cp $path/hypr/*				$config/dwm/
cp -r $path/waybar/*				$config/dwm/
cp -r $path/rofi/*				$config/dwm/
sudo cp $path/gtk-3.0/*			$config/gtk-3.0
cp -r $path/.icons/			$HOME/


cp $path/polybar-scripts/*		$HOME/.polybar-scripts/
cp -r $path/scripts/*			$HOME/.scripts/

cp $path/bash_profile			$HOME/.bash_profile
cp $path/bashrc				$HOME/.bashrc
cp $path/vimrc				$HOME/.vimrc
cp $path/profile			$HOME/.profile

#X11
mkdir -p $config/X11/.xinitrc
cp $path/xinitrc			$config/X11/.xinitrc

mkdir -p $config/gtk-2.0/
cp -r $path/gtk-2.0			$config/
cp $path/compton.conf			$config/compton.conf

sudo cp $path/lightdm/*			/etc/lightdm/

#Generating wallpaper list for gnome-settings
python << END

import os
import xml.etree.cElementTree as ET
workdir = os.getcwd()
os.chdir('/usr/share/backgrounds')
root = ET.Element("wallpapers")
def is_image(image_name):
    if image_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        return True
    else:
        print(image_name + ' is not supported image. It wil not be included into xml file' )
        return False

def add_to_xml(filename):
		wallpaper = ET.SubElement(root, "wallpaper", deleted="false")
		ET.SubElement(wallpaper, "name").text=filename
		ET.SubElement(wallpaper, "filename").text=filename
		ET.SubElement(wallpaper, "options").text='zoom'
		ET.SubElement(root, "pcolor").text='#ffffff'
		ET.SubElement(root, "scolor").text='#000000'
def recursive():
    ls = os.listdir(os.getcwd())
    for i in ls:
        is_dir = os.path.isdir(i)
        if is_dir == True:
            dir_before = os.getcwd()
            os.chdir(dir_before + '/' + i)
            recursive()
            os.chdir(dir_before)
            

        else:
            dir = (os.getcwd() + '/' + i)
            #print(dir)
            #is_image(i)
            #add_to_xml(is_image(i))
            image = is_image(i)
            if image == True:
                add_to_xml(dir)


recursive()

tree = ET.ElementTree(root)
os.chdir(workdir)
tree.write("gnome-backgrounds.xml")
END
sudo mkdir -p /usr/share/gnome-background-properties/
xmllint --format gnome-backgrounds.xml >> cos.xml
sudo cp cos.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
rm cos.xml
rm gnome-backgrounds.xml


sync

echo "Done! Enjoy"
