#!/bin/sh
. "${HOME}/.cache/wal/colors.sh"
alias dmenu='dmenu -h 25 -l 20 -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"'


pgrep -x dmenu && exit

mountable=$(lsblk -lp | grep "part  $" | grep /dev/sd[f-z] | awk '{print $1, "(" $4 ")"}')
[[("$mountable" == "")]] && exit 1
chosen=$(echo "$mountable" | dmenu -i -p  "Mount witch drive?" | awk '{print $1}')
[[("$chosen" == "")]] && exit 1
note=$(udisksctl mount -b $chosen)

if [[("$chosen" == "")]]; then

	notify-send --urgency=critical "cannot mount $chosen"
else
	notify-send "$note"
	echo $note
fi


