#!/bin/sh
#route -n | grep 'UG[ \t]' | awk '{print $2}'
gateway=$(route -n | grep 'UG[ \t]' | awk '{print $2}' | head -n 1)
echo $gateway

nmcli con up id student-ki
sudo route add default gw $gateway 
