#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"
alias dmenu='dmenu -h 25 -l 20 -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"'

pgrep -x dmenu && exit

avaliable=$(nmcli device wifi list | awk '{print $2}')
echo $avaliable
