#!/bin/python

import os
import subprocess
import re

result = subprocess.run(['efibootmgr'],text=True, stdout=subprocess.PIPE)
output = str(result.stdout)

lines = output.splitlines(True)
for i in lines:
	if "Windows Boot Manager" in i:
		line_matched = i
		exit

if not line_matched:
	print("no windows found")
line_splited = line_matched.split("* ")
important_part = line_splited[0]
boot_id = important_part.replace("Boot","")
#print(boot_id)
command = "sudo efibootmgr -n " + boot_id
os.system(command)
os.system("systemctl reboot")
